LOAD DATA LOCAL INFILE '~/data/movie.del' INTO TABLE CS143.Movie
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE '~/data/actor1.del' INTO TABLE CS143.Actor
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE '~/data/actor2.del' INTO TABLE CS143.Actor
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE '~/data/actor3.del' INTO TABLE CS143.Actor
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE '~/data/director.del' INTO TABLE CS143.Director
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE '~/data/moviegenre.del' INTO TABLE CS143.MovieGenre
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE '~/data/moviedirector.del' INTO TABLE CS143.MovieDirector
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE '~/data/movieactor1.del' INTO TABLE CS143.MovieActor
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE '~/data/movieactor2.del' INTO TABLE CS143.MovieActor
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
INSERT INTO CS143.MaxPersonID VALUES (69000);
INSERT INTO CS143.MaxMovieID VALUES (4750);